# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backgroundEdit.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_backgroundEdit(object):
    def setupUi(self, backgroundEdit):
        backgroundEdit.setObjectName("backgroundEdit")
        backgroundEdit.resize(800, 329)
        self.centralwidget = QtWidgets.QWidget(backgroundEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioComment = QtWidgets.QRadioButton(self.centralwidget)
        self.radioComment.setObjectName("radioComment")
        self.verticalLayout.addWidget(self.radioComment)
        self.commentText = QtWidgets.QLineEdit(self.centralwidget)
        self.commentText.setText("")
        self.commentText.setObjectName("commentText")
        self.verticalLayout.addWidget(self.commentText)
        self.radioAnnounce = QtWidgets.QRadioButton(self.centralwidget)
        self.radioAnnounce.setObjectName("radioAnnounce")
        self.verticalLayout.addWidget(self.radioAnnounce)
        self.radioMusic = QtWidgets.QRadioButton(self.centralwidget)
        self.radioMusic.setObjectName("radioMusic")
        self.verticalLayout.addWidget(self.radioMusic)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.anyTimeCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.anyTimeCheckbox.setObjectName("anyTimeCheckbox")
        self.horizontalLayout_3.addWidget(self.anyTimeCheckbox)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.startTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.startTime.setObjectName("startTime")
        self.horizontalLayout_3.addWidget(self.startTime)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.endTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.endTime.setObjectName("endTime")
        self.horizontalLayout_3.addWidget(self.endTime)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectFileButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFileButton.sizePolicy().hasHeightForWidth())
        self.selectFileButton.setSizePolicy(sizePolicy)
        self.selectFileButton.setObjectName("selectFileButton")
        self.horizontalLayout_2.addWidget(self.selectFileButton)
        self.fileNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.horizontalLayout_2.addWidget(self.fileNameLabel)
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_2.addWidget(self.playButton)
        self.loadDirButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadDirButton.sizePolicy().hasHeightForWidth())
        self.loadDirButton.setSizePolicy(sizePolicy)
        self.loadDirButton.setObjectName("loadDirButton")
        self.horizontalLayout_2.addWidget(self.loadDirButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.insertRepeatButton = QtWidgets.QPushButton(self.centralwidget)
        self.insertRepeatButton.setObjectName("insertRepeatButton")
        self.horizontalLayout_4.addWidget(self.insertRepeatButton)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.repeatCount = QtWidgets.QSpinBox(self.centralwidget)
        self.repeatCount.setMaximum(999)
        self.repeatCount.setProperty("value", 5)
        self.repeatCount.setObjectName("repeatCount")
        self.horizontalLayout_4.addWidget(self.repeatCount)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.appluButton = QtWidgets.QPushButton(self.centralwidget)
        self.appluButton.setObjectName("appluButton")
        self.horizontalLayout.addWidget(self.appluButton)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        backgroundEdit.setCentralWidget(self.centralwidget)

        self.retranslateUi(backgroundEdit)
        self.selectFileButton.clicked.connect(backgroundEdit.selectFileButtonClicked)
        self.playButton.clicked.connect(backgroundEdit.playButtonClicked)
        self.insertRepeatButton.clicked.connect(backgroundEdit.repeatButtonClicked)
        self.loadDirButton.clicked.connect(backgroundEdit.loadAllButtonClicked)
        self.radioMusic.clicked.connect(backgroundEdit.enableParts)
        self.radioAnnounce.clicked.connect(backgroundEdit.enableParts)
        self.anyTimeCheckbox.clicked.connect(backgroundEdit.enableParts)
        self.radioComment.clicked.connect(backgroundEdit.enableParts)
        self.cancelButton.clicked.connect(backgroundEdit.cancelButtonClicked)
        self.appluButton.clicked.connect(backgroundEdit.applyButtonClicked)
        QtCore.QMetaObject.connectSlotsByName(backgroundEdit)

    def retranslateUi(self, backgroundEdit):
        _translate = QtCore.QCoreApplication.translate
        backgroundEdit.setWindowTitle(_translate("backgroundEdit", "Edit/Create Background Entry"))
        self.radioComment.setText(_translate("backgroundEdit", "Comment"))
        self.radioAnnounce.setText(_translate("backgroundEdit", "Announcement"))
        self.radioMusic.setText(_translate("backgroundEdit", "Music"))
        self.anyTimeCheckbox.setText(_translate("backgroundEdit", "Any Time"))
        self.label_2.setText(_translate("backgroundEdit", "Start Time Limit"))
        self.label.setText(_translate("backgroundEdit", "End time limit"))
        self.selectFileButton.setText(_translate("backgroundEdit", "Select File"))
        self.fileNameLabel.setText(_translate("backgroundEdit", "<file-name>"))
        self.playButton.setText(_translate("backgroundEdit", "Play"))
        self.loadDirButton.setText(_translate("backgroundEdit", "Load All Music In Directory"))
        self.insertRepeatButton.setText(_translate("backgroundEdit", "Insert Repeated Announcement"))
        self.label_3.setText(_translate("backgroundEdit", "Number of songs / announcment"))
        self.appluButton.setText(_translate("backgroundEdit", "Apply"))
        self.cancelButton.setText(_translate("backgroundEdit", "Cancel"))
